import java.util.Properties

// No `org.jetbrains.kotlin.android` here: AGP 9+ has built-in Kotlin support
// and applying that plugin alongside it is a build error. See
// https://developer.android.com/build/migrate-to-built-in-kotlin. The
// compose/serialization/ksp sub-plugins below are still applied separately —
// built-in Kotlin only subsumes the base kotlin-android plugin, not these.
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.ktlint)
}

// CI supplies signing material via environment variables; local builds may use
// the gitignored properties file. Partial configuration must never ship unsigned.
val releaseSigning =
    run {
        val env =
            mapOf(
                "storeFile" to "EMOTION_TRACKER_KEYSTORE_FILE",
                "storePassword" to "EMOTION_TRACKER_KEYSTORE_PASSWORD",
                "keyAlias" to "EMOTION_TRACKER_KEY_ALIAS",
                "keyPassword" to "EMOTION_TRACKER_KEY_PASSWORD",
            ).mapValues { (_, name) -> providers.environmentVariable(name).orNull }
        val file = rootProject.file("keystore.properties")
        val material =
            when {
                env.values.any { it != null } -> env
                file.exists() -> {
                    val properties = Properties().apply { file.inputStream().use(::load) }
                    env.keys.associateWith { properties.getProperty(it) }
                }
                else -> null
            }
        material
            ?.also {
                require(it.values.none { value -> value.isNullOrBlank() }) {
                    "Release signing requires storeFile, storePassword, keyAlias and keyPassword. See docs/secrets.md."
                }
            }?.mapValues { (_, value) -> value!! }
    }

android {
    namespace = "dev.co508.emotiontracker"
    compileSdk = 37

    defaultConfig {
        applicationId = "dev.co508.emotiontracker"
        // API 26 (Android 8.0) gives us java.time natively, so entry timestamps
        // don't need core library desugaring. Revisit only with a concrete
        // reach requirement below that floor.
        minSdk = 26
        targetSdk = 36
        // Generated by scripts/sync-version.sh; keep literals for F-Droid's parser.
        versionCode = 1000
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            releaseSigning?.let { material ->
                signingConfigs.create("release") {
                    storeFile = rootProject.file(material.getValue("storeFile"))
                    storePassword = material.getValue("storePassword")
                    keyAlias = material.getValue("keyAlias")
                    keyPassword = material.getValue("keyPassword")
                }
                signingConfig = signingConfigs.getByName("release")
            }
        }
        debug {
            applicationIdSuffix = ".debug"
        }
    }

    // Built-in Kotlin's jvmTarget defaults to targetCompatibility below, so
    // there's no separate `kotlin { compilerOptions { ... } }` block needed.
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    // F-Droid builds must not include Google's opaque dependency metadata.
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    packaging {
        // Preserve upstream native libraries across builders with different NDKs.
        jniLibs { keepDebugSymbols += "**/*.so" }
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

ktlint {
    // Uses the ktlint core version bundled with the Gradle plugin above.
    android.set(true)
}

ksp {
    // Room schema history, for migration tests as the schema evolves.
    // Commit app/schemas/ — it's small and it's how Room verifies migrations.
    arg("room.schemaLocation", "$projectDir/schemas")
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.navigation.compose)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.core)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    debugImplementation(libs.compose.ui.tooling)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.serialization.json)
    testImplementation(libs.kotlinx.coroutines.test)
}
